---
title: "Homelab"
subtitle: "Dries"
logo: "/assets/tools/sunville.png"

header: false
footer: false # Set false if you want to hide it.

stylesheet:
  - "/assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "//General"
    icon: "fas fa-github"
    items:
      - name: "CommaFeed"
        logo: "/assets/tools/CommaFeed.svg.png" # Change github.png to the name of your own custom icon!
        tag: "Sunville"
        tagstyle: "is-primary" # This will display the is-primary color! Try changing it to; is-link, is-info, is-success, is-warning or is-danger!
        url: "http://commafeed-commafeed.tail2d9af5.ts.net:8082/"
        target: "_blank"
      - name: "Excalidraw"
        logo: "/assets/tools/excalidraw.svg" # Change github.png to the name of your own custom icon!
        tag: "Sunville"
        tagstyle: "is-primary" # This will display the is-primary color! Try changing it to; is-link, is-info, is-success, is-warning or is-danger!
        url: "http://excalidraw-excalidraw.tail2d9af5.ts.net/"
        target: "_blank"
  - name: "//Media"
    icon: "fas fa-github"
    items:
      - name: "Plex"
        logo: "/assets/tools/plex.webp" # Change github.png to the name of your own custom icon!
        tag: "Sunville"
        tagstyle: "is-primary" # This will display the is-primary color! Try changing it to; is-link, is-info, is-success, is-warning or is-danger!
        url: "http://media-stack-plex.tail2d9af5.ts.net:32400/"
        target: "_blank"
      - name: "Overseerr"
        logo: "/assets/tools/Overseerr.png" # Change github.png to the name of your own custom icon!
        tag: "Sunville"
        tagstyle: "is-primary" # This will display the is-primary color! Try changing it to; is-link, is-info, is-success, is-warning or is-danger!
        url: "http://media-stack-overseerr.tail2d9af5.ts.net:5055/"
        target: "_blank"
      - name: "Radarr"
        logo: "/assets/tools/radarr.png" # Change github.png to the name of your own custom icon!
        tag: "Sunville"
        tagstyle: "is-primary" # This will display the is-primary color! Try changing it to; is-link, is-info, is-success, is-warning or is-danger!
        url: "http://media-stack-radarr.tail2d9af5.ts.net:7878/"
        target: "_blank"
      - name: "Sonarr"
        logo: "/assets/tools/sonarr.png" # Change github.png to the name of your own custom icon!
        tag: "Sunville"
        tagstyle: "is-primary" # This will display the is-primary color! Try changing it to; is-link, is-info, is-success, is-warning or is-danger!
        url: "http://media-stack-sonarr.tail2d9af5.ts.net:8989/"
        target: "_blank"
  - name: "//Dashboards"
    icon: "fas fa-github"
    items:
      - name: "Grafana"
        logo: "/assets/tools/grafana.png" # Change github.png to the name of your own custom icon!
        tag: "Sunville"
        tagstyle: "is-primary" # This will display the is-primary color! Try changing it to; is-link, is-info, is-success, is-warning or is-danger!
        url: "http://monitoring-grafana.tail2d9af5.ts.net:3000/d/becuowssfebcwa/scraping?orgId=1"
        target: "_blank"
      - name: "Kubernetes"
        logo: "/assets/tools/kubernetes.png" # Change github.png to the name of your own custom icon!
        tag: "Sunville"
        tagstyle: "is-primary" # This will display the is-primary color! Try changing it to; is-link, is-info, is-success, is-warning or is-danger!
        url: "https://dashboard.tail2d9af5.ts.net/#/workloads?namespace=_all"
        target: "_blank"
